In [1]:
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [1]:
import pandas as pd
df = pd.read_csv('HADS1.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43468 entries, 0 to 43467
Data columns (total 21 columns):
StudentID             43468 non-null float64
IQScore               43458 non-null float64
Current Education     43460 non-null object
Exercise              43457 non-null object
Gender                43468 non-null object
Height                43462 non-null float64
Weight                43463 non-null float64
Age                   43454 non-null float64
Peer Pressure         43462 non-null object
Living with Family    43457 non-null object
Past History          43463 non-null object
Smoke                 43463 non-null object
Q1                    43468 non-null int64
Q2                    43468 non-null int64
Q3                    43468 non-null int64
Q4                    43468 non-null int64
Q5                    43468 non-null int64
Q6                    43468 non-null int64
Q7                    43468 non-null int64
HADS                  43468 non-null int64
HADSbin               43468 non-null object
dtypes: float64(5), int64(8), object(8)
memory usage: 5.6+ MB

In [2]:
df = pd.read_csv('HADS1.csv')
df.head()

,StudentID,IQScore,Current Education,Exercise,Gender,Height,Weight,Age,Peer Pressure,Living with Family,...,Smoke,Q1,Q2,Q3,Q4,Q5,Q6,Q7,HADS,HADSbin
0,3144076.0,90.0,G,None,M,5.0,62.0,21.0,Y,N,...,Y,3,3,2,2,3,3,3,19,Abnormal
1,8046964.0,96.0,G,None,M,4.5,69.0,18.0,Y,N,...,Y,3,3,3,2,3,3,2,19,Abnormal
2,7843714.0,112.0,G,None,M,5.2,68.0,20.0,Y,Y,...,Y,3,3,2,3,2,2,3,18,Abnormal
3,4036017.0,98.0,G,None,M,6.2,49.0,19.0,Y,Y,...,Y,3,2,3,3,2,2,3,18,Abnormal
4,9910417.0,104.0,PG,Moderate,F,5.6,77.0,22.0,N,Y,...,N,2,2,1,1,2,0,0,8,Borderline Abnormal

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43468 entries, 0 to 43467
Data columns (total 21 columns):
StudentID             43468 non-null float64
IQScore               43458 non-null float64
Current Education     43460 non-null object
Exercise              43457 non-null object
Gender                43468 non-null object
Height                43462 non-null float64
Weight                43463 non-null float64
Age                   43454 non-null float64
Peer Pressure         43462 non-null object
Living with Family    43457 non-null object
Past History          43463 non-null object
Smoke                 43463 non-null object
Q1                    43468 non-null int64
Q2                    43468 non-null int64
Q3                    43468 non-null int64
Q4                    43468 non-null int64
Q5                    43468 non-null int64
Q6                    43468 non-null int64
Q7                    43468 non-null int64
HADS                  43468 non-null int64
HADSbin               43468 non-null object
dtypes: float64(5), int64(8), object(8)
memory usage: 5.6+ MB

In [4]:
df.drop(['Q1','Q2','Q3','Q4','Q5','Q6','Q7','HADS'],axis = 1,inplace = True)

In [5]:
df.head()

,StudentID,IQScore,Current Education,Exercise,Gender,Height,Weight,Age,Peer Pressure,Living with Family,Past History,Smoke,HADSbin
0,3144076.0,90.0,G,None,M,5.0,62.0,21.0,Y,N,Y,Y,Abnormal
1,8046964.0,96.0,G,None,M,4.5,69.0,18.0,Y,N,Y,Y,Abnormal
2,7843714.0,112.0,G,None,M,5.2,68.0,20.0,Y,Y,Y,Y,Abnormal
3,4036017.0,98.0,G,None,M,6.2,49.0,19.0,Y,Y,Y,Y,Abnormal
4,9910417.0,104.0,PG,Moderate,F,5.6,77.0,22.0,N,Y,Y,N,Borderline Abnormal

In [6]:
df.isna().sum()

StudentID              0
IQScore               10
Current Education      8
Exercise              11
Gender                 0
Height                 6
Weight                 5
Age                   14
Peer Pressure          6
Living with Family    11
Past History           5
Smoke                  5
HADSbin                0
dtype: int64

In [7]:
df.dropna()

,StudentID,IQScore,Current Education,Exercise,Gender,Height,Weight,Age,Peer Pressure,Living with Family,Past History,Smoke,HADSbin
0,3144076.0,90.0,G,None,M,5.0,62.0,21.0,Y,N,Y,Y,Abnormal
1,8046964.0,96.0,G,None,M,4.5,69.0,18.0,Y,N,Y,Y,Abnormal
2,7843714.0,112.0,G,None,M,5.2,68.0,20.0,Y,Y,Y,Y,Abnormal
3,4036017.0,98.0,G,None,M,6.2,49.0,19.0,Y,Y,Y,Y,Abnormal
4,9910417.0,104.0,PG,Moderate,F,5.6,77.0,22.0,N,Y,Y,N,Borderline Abnormal
5,1596235.0,105.0,PG,Moderate,F,5.9,70.0,26.0,N,Y,N,N,Borderline Abnormal
6,620289.0,92.0,PG,Moderate,F,4.7,71.0,22.0,N,Y,N,N,Borderline Abnormal
7,9778010.0,99.0,PG,Moderate,F,5.6,48.0,23.0,N,Y,N,Y,Normal
10,6145392.0,96.0,PG,Heavy,M,5.7,53.0,28.0,N,Y,N,N,Normal
11,7287561.0,89.0,S,None,M,4.9,45.0,13.0,N,N,Y,N,Normal
12,9547882.0,111.0,S,None,M,4.9,35.0,12.0,N,N,N,Y,Normal
13,4293181.0,87.0,S,None,F,5.4,49.0,13.0,Y,N,N,Y,Normal
14,5049198.0,104.0,S,Moderate,F,5.3,41.0,12.0,N,Y,N,N,Normal
15,871266.0,115.0,S,Heavy,F,4.9,47.0,13.0,N,Y,Y,N,Normal
16,8900872.0,100.0,S,Heavy,F,5.1,48.0,14.0,Y,Y,Y,N,Normal
17,6848503.0,106.0,S,Heavy,F,5.3,43.0,13.0,N,Y,N,N,Normal
18,1129600.0,88.0,S,Heavy,F,5.0,38.0,14.0,Y,Y,N,N,Normal
19,5546681.0,99.0,G,None,M,5.4,39.0,21.0,Y,N,Y,Y,Abnormal
20,6552804.0,91.0,G,None,M,5.4,40.0,18.0,Y,N,Y,Y,Abnormal
21,9443344.0,107.0,G,None,M,5.0,46.0,20.0,Y,Y,Y,Y,Abnormal
22,8991943.0,109.0,G,None,M,4.8,37.0,19.0,Y,Y,Y,Y,Abnormal
23,7147228.0,92.0,G,None,M,5.5,43.0,18.0,N,Y,Y,Y,Abnormal
24,3103269.0,109.0,G,None,M,5.3,49.0,18.0,Y,Y,Y,Y,Abnormal
25,546779.0,115.0,G,Moderate,M,5.1,43.0,18.0,Y,N,Y,Y,Abnormal
26,1619123.0,104.0,PG,None,M,4.9,46.0,27.0,Y,N,Y,Y,Abnormal
27,9910930.0,112.0,PG,None,M,4.9,39.0,26.0,Y,N,Y,Y,Abnormal
28,4872049.0,92.0,PG,None,M,5.3,44.0,26.0,Y,N,Y,Y,Borderline Abnormal
29,1436066.0,108.0,PG,None,F,5.2,43.0,27.0,Y,N,N,N,Borderline Abnormal
30,6326932.0,94.0,PG,None,F,4.8,44.0,25.0,N,N,N,Y,Borderline Abnormal
31,1402573.0,110.0,PG,Moderate,F,5.2,46.0,24.0,N,N,N,Y,Borderline Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...
43429,4228449.0,108.0,PG,Moderate,F,5.6,67.0,23.0,N,Y,N,Y,Normal
43430,4374359.0,93.0,PG,Heavy,M,5.5,61.0,27.0,N,Y,N,N,Normal
43431,452319.0,101.0,PG,Heavy,M,5.1,51.0,24.0,N,Y,N,N,Normal
43432,9209467.0,91.0,PG,Heavy,M,4.5,65.0,28.0,N,Y,N,N,Normal
43433,4770263.0,88.0,S,None,M,5.2,70.0,13.0,N,N,Y,N,Normal
43434,4156483.0,98.0,S,None,M,6.1,80.0,12.0,N,N,N,Y,Normal
43435,1315119.0,107.0,S,None,F,4.5,53.0,13.0,Y,N,N,Y,Normal
43436,3804029.0,115.0,S,Moderate,F,4.8,75.0,12.0,N,Y,N,N,Normal
43437,7154369.0,105.0,S,Heavy,F,4.9,77.0,13.0,N,Y,Y,N,Normal
43438,7677383.0,95.0,S,Heavy,F,5.3,76.0,14.0,Y,Y,Y,N,Normal
43439,5717939.0,86.0,S,Heavy,F,4.7,52.0,13.0,N,Y,N,N,Normal
43440,2256077.0,108.0,S,Heavy,F,6.0,78.0,14.0,Y,Y,N,N,Normal
43441,5607902.0,108.0,G,None,M,4.8,80.0,21.0,Y,N,Y,Y,Abnormal
43442,3041314.0,107.0,G,None,M,5.5,59.0,18.0,Y,N,Y,Y,Abnormal
43443,676901.0,98.0,G,None,M,5.5,53.0,20.0,Y,Y,Y,Y,Abnormal
43444,4214801.0,89.0,G,None,M,4.6,68.0,19.0,Y,Y,Y,Y,Abnormal
43445,9367213.0,109.0,G,None,M,5.2,52.0,18.0,N,Y,Y,Y,Abnormal
43446,6942577.0,114.0,G,None,M,4.7,63.0,18.0,Y,Y,Y,Y,Abnormal
43447,4753401.0,91.0,G,Moderate,M,5.6,65.0,18.0,Y,N,Y,Y,Abnormal
43448,17138.0,112.0,PG,None,M,4.5,64.0,27.0,Y,N,Y,Y,Abnormal
43449,2134630.0,103.0,PG,None,M,5.9,55.0,26.0,Y,N,Y,Y,Abnormal
43458,9888846.0,92.0,PG,Moderate,F,5.0,53.0,23.0,N,Y,N,Y,Normal
43459,3493712.0,115.0,PG,Heavy,M,4.5,49.0,27.0,N,Y,N,N,Normal
43460,452430.0,95.0,PG,Heavy,M,6.2,68.0,24.0,N,Y,N,N,Normal
43462,1055604.0,111.0,S,None,F,5.6,46.0,13.0,Y,N,N,Y,Normal
43463,5373529.0,99.0,S,Moderate,F,4.8,55.0,12.0,N,Y,N,N,Normal
43464,3620796.0,89.0,S,Heavy,F,5.5,80.0,13.0,N,Y,Y,N,Normal
43465,6206208.0,94.0,S,Heavy,F,4.9,50.0,14.0,Y,Y,Y,N,Normal
43466,2687773.0,104.0,S,Heavy,F,5.4,77.0,13.0,N,Y,N,N,Normal
43467,3686126.0,102.0,S,Heavy,F,4.5,60.0,14.0,Y,Y,N,N,Normal

In [8]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
5        False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
         ...
43438    False
43439    False
43440    False
43441    False
43442    False
43443    False
43444    False
43445    False
43446    False
43447    False
43448    False
43449    False
43450    False
43451    False
43452    False
43453    False
43454    False
43455    False
43456    False
43457    False
43458    False
43459    False
43460    False
43461    False
43462    False
43463    False
43464    False
43465    False
43466    False
43467    False
Length: 43468, dtype: bool

In [9]:
df.drop_duplicates

<bound method DataFrame.drop_duplicates of        StudentID  IQScore Current Education  Exercise Gender  Height  Weight  \
0      3144076.0     90.0                 G      None      M     5.0    62.0
1      8046964.0     96.0                 G      None      M     4.5    69.0
2      7843714.0    112.0                 G      None      M     5.2    68.0
3      4036017.0     98.0                 G      None      M     6.2    49.0
4      9910417.0    104.0                PG  Moderate      F     5.6    77.0
5      1596235.0    105.0                PG  Moderate      F     5.9    70.0
6       620289.0     92.0                PG  Moderate      F     4.7    71.0
7      9778010.0     99.0                PG  Moderate      F     5.6    48.0
8       222071.0      NaN                PG     Heavy      M     4.6    77.0
9       101289.0      NaN                PG     Heavy      M     5.8    62.0
10     6145392.0     96.0                PG     Heavy      M     5.7    53.0
11     7287561.0     89.0                 S      None      M     4.9    45.0
12     9547882.0    111.0                 S      None      M     4.9    35.0
13     4293181.0     87.0                 S      None      F     5.4    49.0
14     5049198.0    104.0                 S  Moderate      F     5.3    41.0
15      871266.0    115.0                 S     Heavy      F     4.9    47.0
16     8900872.0    100.0                 S     Heavy      F     5.1    48.0
17     6848503.0    106.0                 S     Heavy      F     5.3    43.0
18     1129600.0     88.0                 S     Heavy      F     5.0    38.0
19     5546681.0     99.0                 G      None      M     5.4    39.0
20     6552804.0     91.0                 G      None      M     5.4    40.0
21     9443344.0    107.0                 G      None      M     5.0    46.0
22     8991943.0    109.0                 G      None      M     4.8    37.0
23     7147228.0     92.0                 G      None      M     5.5    43.0
24     3103269.0    109.0                 G      None      M     5.3    49.0
25      546779.0    115.0                 G  Moderate      M     5.1    43.0
26     1619123.0    104.0                PG      None      M     4.9    46.0
27     9910930.0    112.0                PG      None      M     4.9    39.0
28     4872049.0     92.0                PG      None      M     5.3    44.0
29     1436066.0    108.0                PG      None      F     5.2    43.0
...          ...      ...               ...       ...    ...     ...     ...
43438  7677383.0     95.0                 S     Heavy      F     5.3    76.0
43439  5717939.0     86.0                 S     Heavy      F     4.7    52.0
43440  2256077.0    108.0                 S     Heavy      F     6.0    78.0
43441  5607902.0    108.0                 G      None      M     4.8    80.0
43442  3041314.0    107.0                 G      None      M     5.5    59.0
43443   676901.0     98.0                 G      None      M     5.5    53.0
43444  4214801.0     89.0                 G      None      M     4.6    68.0
43445  9367213.0    109.0                 G      None      M     5.2    52.0
43446  6942577.0    114.0                 G      None      M     4.7    63.0
43447  4753401.0     91.0                 G  Moderate      M     5.6    65.0
43448    17138.0    112.0                PG      None      M     4.5    64.0
43449  2134630.0    103.0                PG      None      M     5.9    55.0
43450  5327520.0     99.0               NaN      None      M     6.1    79.0
43451  2183496.0    112.0               NaN      None      F     5.9    64.0
43452    84344.0     87.0                PG      None      F     5.4    50.0
43453  3771515.0    100.0                PG  Moderate      F     6.0    49.0
43454  2644437.0     96.0                PG  Moderate      F     6.0    71.0
43455  9181474.0    104.0                PG  Moderate      F     5.0    77.0
43456  7597569.0     96.0                PG  Moderate      F     5.2    70.0
43457  1039769.0     96.0                PG  Moderate      F     4.7    50.0
43458  9888846.0     92.0                PG  Moderate      F     5.0    53.0
43459  3493712.0    115.0                PG     Heavy      M     4.5    49.0
43460   452430.0     95.0                PG     Heavy      M     6.2    68.0
43461  4966740.0    113.0                PG     Heavy      M     NaN    62.0
43462  1055604.0    111.0                 S      None      F     5.6    46.0
43463  5373529.0     99.0                 S  Moderate      F     4.8    55.0
43464  3620796.0     89.0                 S     Heavy      F     5.5    80.0
43465  6206208.0     94.0                 S     Heavy      F     4.9    50.0
43466  2687773.0    104.0                 S     Heavy      F     5.4    77.0
43467  3686126.0    102.0                 S     Heavy      F     4.5    60.0

        Age Peer Pressure Living with Family Past History Smoke  \
0      21.0             Y                  N            Y     Y
1      18.0             Y                  N            Y     Y
2      20.0             Y                  Y            Y     Y
3      19.0             Y                  Y            Y     Y
4      22.0             N                  Y            Y     N
5      26.0             N                  Y            N     N
6      22.0             N                  Y            N     N
7      23.0             N                  Y            N     Y
8      27.0             N                  Y            N     N
9      24.0             N                  Y            N     N
10     28.0             N                  Y            N     N
11     13.0             N                  N            Y     N
12     12.0             N                  N            N     Y
13     13.0             Y                  N            N     Y
14     12.0             N                  Y            N     N
15     13.0             N                  Y            Y     N
16     14.0             Y                  Y            Y     N
17     13.0             N                  Y            N     N
18     14.0             Y                  Y            N     N
19     21.0             Y                  N            Y     Y
20     18.0             Y                  N            Y     Y
21     20.0             Y                  Y            Y     Y
22     19.0             Y                  Y            Y     Y
23     18.0             N                  Y            Y     Y
24     18.0             Y                  Y            Y     Y
25     18.0             Y                  N            Y     Y
26     27.0             Y                  N            Y     Y
27     26.0             Y                  N            Y     Y
28     26.0             Y                  N            Y     Y
29     27.0             Y                  N            N     N
...     ...           ...                ...          ...   ...
43438  14.0             Y                  Y            Y     N
43439  13.0             N                  Y            N     N
43440  14.0             Y                  Y            N     N
43441  21.0             Y                  N            Y     Y
43442  18.0             Y                  N            Y     Y
43443  20.0             Y                  Y            Y     Y
43444  19.0             Y                  Y            Y     Y
43445  18.0             N                  Y            Y     Y
43446  18.0             Y                  Y            Y     Y
43447  18.0             Y                  N            Y     Y
43448  27.0             Y                  N            Y     Y
43449  26.0             Y                  N            Y     Y
43450   NaN             Y                  N            Y     Y
43451   NaN             Y                  N            N     N
43452   NaN           NaN                NaN            N     Y
43453   NaN           NaN                NaN            N     Y
43454  28.0           NaN                NaN            Y     N
43455  22.0           NaN                NaN            Y     N
43456  26.0           NaN                NaN            N     N
43457  22.0           NaN                NaN            N     N
43458  23.0             N                  Y            N     Y
43459  27.0             N                  Y            N     N
43460  24.0             N                  Y            N     N
43461  28.0             N                  Y            N     N
43462  13.0             Y                  N            N     Y
43463  12.0             N                  Y            N     N
43464  13.0             N                  Y            Y     N
43465  14.0             Y                  Y            Y     N
43466  13.0             N                  Y            N     N
43467  14.0             Y                  Y            N     N

                   HADSbin
0                 Abnormal
1                 Abnormal
2                 Abnormal
3                 Abnormal
4      Borderline Abnormal
5      Borderline Abnormal
6      Borderline Abnormal
7                   Normal
8                   Normal
9                   Normal
10                  Normal
11                  Normal
12                  Normal
13                  Normal
14                  Normal
15                  Normal
16                  Normal
17                  Normal
18                  Normal
19                Abnormal
20                Abnormal
21                Abnormal
22                Abnormal
23                Abnormal
24                Abnormal
25                Abnormal
26                Abnormal
27                Abnormal
28     Borderline Abnormal
29     Borderline Abnormal
...                    ...
43438               Normal
43439               Normal
43440               Normal
43441             Abnormal
43442             Abnormal
43443             Abnormal
43444             Abnormal
43445             Abnormal
43446             Abnormal
43447             Abnormal
43448             Abnormal
43449             Abnormal
43450  Borderline Abnormal
43451  Borderline Abnormal
43452  Borderline Abnormal
43453  Borderline Abnormal
43454  Borderline Abnormal
43455  Borderline Abnormal
43456  Borderline Abnormal
43457  Borderline Abnormal
43458               Normal
43459               Normal
43460               Normal
43461               Normal
43462               Normal
43463               Normal
43464               Normal
43465               Normal
43466               Normal
43467               Normal

[43468 rows x 13 columns]>

In [10]:
df.head()

,StudentID,IQScore,Current Education,Exercise,Gender,Height,Weight,Age,Peer Pressure,Living with Family,Past History,Smoke,HADSbin
0,3144076.0,90.0,G,None,M,5.0,62.0,21.0,Y,N,Y,Y,Abnormal
1,8046964.0,96.0,G,None,M,4.5,69.0,18.0,Y,N,Y,Y,Abnormal
2,7843714.0,112.0,G,None,M,5.2,68.0,20.0,Y,Y,Y,Y,Abnormal
3,4036017.0,98.0,G,None,M,6.2,49.0,19.0,Y,Y,Y,Y,Abnormal
4,9910417.0,104.0,PG,Moderate,F,5.6,77.0,22.0,N,Y,Y,N,Borderline Abnormal

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43468 entries, 0 to 43467
Data columns (total 13 columns):
StudentID             43468 non-null float64
IQScore               43458 non-null float64
Current Education     43460 non-null object
Exercise              43457 non-null object
Gender                43468 non-null object
Height                43462 non-null float64
Weight                43463 non-null float64
Age                   43454 non-null float64
Peer Pressure         43462 non-null object
Living with Family    43457 non-null object
Past History          43463 non-null object
Smoke                 43463 non-null object
HADSbin               43468 non-null object
dtypes: float64(5), object(8)
memory usage: 3.0+ MB

In [12]:
j = []
for i in df.itertuples(): 
    if(i[3] == 'G'):
        j.append(1)
    elif(i[3] == 'PG'):
        j.append(2)
    else:
        j.append(0)
j

[1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 ...]

In [13]:
df['CurEdu'] = j

In [15]:
j = []
for i in df.itertuples(): 
    if(i[4] == 'None'):
        j.append(0)
    elif(i[4] == 'Heavy'):
        j.append(2)
    else:
        j.append(1)
df['ExerciseDone'] = j

In [16]:
j = []
for i in df.itertuples(): 
    if(i[5] == 'M'):
        j.append(1)
    else:
        j.append(0)
df['Sex'] = j

In [17]:
j = []
for i in df.itertuples(): 
    if(i[9] == 'Y'):
        j.append(1)
    else:
        j.append(0)
df['PP'] = j

In [18]:
j = []
for i in df.itertuples(): 
    if(i[10] == 'Y'):
        j.append(1)
    else:
        j.append(0)
df['LF'] = j

In [19]:
j = []
for i in df.itertuples(): 
    if(i[11] == 'Y'):
        j.append(1)
    else:
        j.append(0)
df['PH'] = j

In [20]:
j = []
for i in df.itertuples(): 
    if(i[12] == 'Y'):
        j.append(1)
    else:
        j.append(0)
df['S'] = j

In [21]:
df.head()

,StudentID,IQScore,Current Education,Exercise,Gender,Height,Weight,Age,Peer Pressure,Living with Family,Past History,Smoke,HADSbin,CurEdu,ExerciseDone,Sex,PP,LF,PH,S
0,3144076.0,90.0,G,None,M,5.0,62.0,21.0,Y,N,Y,Y,Abnormal,1,0,1,1,0,1,1
1,8046964.0,96.0,G,None,M,4.5,69.0,18.0,Y,N,Y,Y,Abnormal,1,0,1,1,0,1,1
2,7843714.0,112.0,G,None,M,5.2,68.0,20.0,Y,Y,Y,Y,Abnormal,1,0,1,1,1,1,1
3,4036017.0,98.0,G,None,M,6.2,49.0,19.0,Y,Y,Y,Y,Abnormal,1,0,1,1,1,1,1
4,9910417.0,104.0,PG,Moderate,F,5.6,77.0,22.0,N,Y,Y,N,Borderline Abnormal,2,1,0,0,1,1,0

In [22]:
df['BMI'] = df['Weight']/((0.3048*df['Height'])**2)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43468 entries, 0 to 43467
Data columns (total 21 columns):
StudentID             43468 non-null float64
IQScore               43458 non-null float64
Current Education     43460 non-null object
Exercise              43457 non-null object
Gender                43468 non-null object
Height                43462 non-null float64
Weight                43463 non-null float64
Age                   43454 non-null float64
Peer Pressure         43462 non-null object
Living with Family    43457 non-null object
Past History          43463 non-null object
Smoke                 43463 non-null object
HADSbin               43468 non-null object
CurEdu                43468 non-null int64
ExerciseDone          43468 non-null int64
Sex                   43468 non-null int64
PP                    43468 non-null int64
LF                    43468 non-null int64
PH                    43468 non-null int64
S                     43468 non-null int64
BMI                   43457 non-null float64
dtypes: float64(6), int64(7), object(8)
memory usage: 5.6+ MB

In [24]:
j = []
for i in df.itertuples(): 
    if(i[21]<=16):
        j.append(0)
    elif(i[21]<18.5):
        j.append(1)
    elif(i[21]<25):
        j.append(2)
    elif(i[21]<30):
        j.append(3)
    else:
        j.append(4)
j

[3,
 4,
 3,
 0,
 3,
 2,
 4,
 1,
 4,
 2,
 1,
 2,
 0,
 1,
 0,
 2,
 2,
 1,
 1,
 0,
 0,
 2,
 1,
 0,
 2,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 0,
 1,
 0,
 2,
 2,
 0,
 0,
 1,
 0,
 0,
 2,
 1,
 1,
 1,
 0,
 1,
 2,
 0,
 2,
 2,
 2,
 2,
 2,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 2,
 1,
 2,
 2,
 0,
 2,
 1,
 2,
 0,
 1,
 1,
 2,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 2,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 2,
 1,
 2,
 1,
 1,
 2,
 1,
 2,
 0,
 0,
 1,
 1,
 2,
 1,
 1,
 2,
 0,
 2,
 2,
 0,
 2,
 0,
 0,
 0,
 2,
 0,
 1,
 2,
 1,
 2,
 0,
 2,
 1,
 2,
 2,
 1,
 1,
 1,
 0,
 0,
 1,
 2,
 0,
 2,
 2,
 2,
 2,
 2,
 0,
 1,
 2,
 0,
 2,
 0,
 1,
 1,
 1,
 0,
 2,
 1,
 0,
 2,
 0,
 0,
 0,
 1,
 2,
 0,
 1,
 0,
 0,
 1,
 0,
 2,
 2,
 0,
 0,
 0,
 0,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 0,
 2,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 2,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 2,
 0,
 0,
 1,
 2,
 1,
 2,
 0,
 0,
 1,
 0,
 0,
 2,
 1,
 2,
 0,
 2,
 0,
 0,
 1,
 1,
 2,
 0,
 1,
 2,
 0,
 0,
 2,
 1,
 0,
 1,
 1,
 0,
 2,
 1,
 1,
 2,
 0,
 0,
 1,
 0,
 2,
 1,
 1,
 1,
 1,
 0,
 2,
 2,
 1,
 1,
 2,
 1,
 2,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 2,
 2,
 1,
 0,
 0,
 0,
 2,
 2,
 1,
 1,
 0,
 2,
 2,
 2,
 2,
 0,
 2,
 1,
 0,
 1,
 2,
 2,
 2,
 1,
 0,
 2,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 2,
 0,
 2,
 1,
 1,
 2,
 2,
 2,
 0,
 1,
 2,
 1,
 0,
 2,
 0,
 1,
 0,
 0,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 0,
 2,
 0,
 0,
 0,
 0,
 1,
 2,
 2,
 0,
 2,
 1,
 0,
 0,
 1,
 1,
 1,
 2,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 2,
 0,
 1,
 0,
 2,
 0,
 0,
 2,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 2,
 1,
 2,
 1,
 1,
 0,
 0,
 2,
 1,
 0,
 2,
 0,
 2,
 0,
 2,
 2,
 0,
 1,
 2,
 0,
 0,
 2,
 1,
 2,
 0,
 2,
 1,
 2,
 0,
 0,
 2,
 1,
 1,
 1,
 2,
 1,
 0,
 2,
 2,
 2,
 1,
 1,
 0,
 2,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 2,
 0,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 2,
 1,
 2,
 2,
 1,
 1,
 2,
 2,
 1,
 0,
 1,
 1,
 0,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 2,
 2,
 1,
 1,
 0,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 0,
 2,
 1,
 2,
 2,
 1,
 2,
 1,
 2,
 0,
 0,
 2,
 2,
 2,
 1,
 0,
 1,
 0,
 1,
 2,
 1,
 0,
 0,
 1,
 2,
 0,
 0,
 1,
 0,
 0,
 1,
 2,
 2,
 2,
 2,
 2,
 0,
 1,
 0,
 1,
 2,
 2,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 ...]

In [26]:
df.head()

,StudentID,IQScore,Current Education,Exercise,Gender,Height,Weight,Age,Peer Pressure,Living with Family,...,Smoke,HADSbin,CurEdu,ExerciseDone,Sex,PP,LF,PH,S,BMI
0,3144076.0,90.0,G,None,M,5.0,62.0,21.0,Y,N,...,Y,Abnormal,1,0,1,1,0,1,1,26.694498
1,8046964.0,96.0,G,None,M,4.5,69.0,18.0,Y,N,...,Y,Abnormal,1,0,1,1,0,1,1,36.677028
2,7843714.0,112.0,G,None,M,5.2,68.0,20.0,Y,Y,...,Y,Abnormal,1,0,1,1,1,1,1,27.069005
3,4036017.0,98.0,G,None,M,6.2,49.0,19.0,Y,Y,...,Y,Abnormal,1,0,1,1,1,1,1,13.720906
4,9910417.0,104.0,PG,Moderate,F,5.6,77.0,22.0,N,Y,...,N,Borderline Abnormal,2,1,0,0,1,1,0,26.429244

In [27]:
df['BMIbin'] = j

In [28]:
df.head()

,StudentID,IQScore,Current Education,Exercise,Gender,Height,Weight,Age,Peer Pressure,Living with Family,...,HADSbin,CurEdu,ExerciseDone,Sex,PP,LF,PH,S,BMI,BMIbin
0,3144076.0,90.0,G,None,M,5.0,62.0,21.0,Y,N,...,Abnormal,1,0,1,1,0,1,1,26.694498,3
1,8046964.0,96.0,G,None,M,4.5,69.0,18.0,Y,N,...,Abnormal,1,0,1,1,0,1,1,36.677028,4
2,7843714.0,112.0,G,None,M,5.2,68.0,20.0,Y,Y,...,Abnormal,1,0,1,1,1,1,1,27.069005,3
3,4036017.0,98.0,G,None,M,6.2,49.0,19.0,Y,Y,...,Abnormal,1,0,1,1,1,1,1,13.720906,0
4,9910417.0,104.0,PG,Moderate,F,5.6,77.0,22.0,N,Y,...,Borderline Abnormal,2,1,0,0,1,1,0,26.429244,3

In [29]:
df.drop(['BMI'],axis = 1,inplace=True)

In [30]:
df.head()

,StudentID,IQScore,Current Education,Exercise,Gender,Height,Weight,Age,Peer Pressure,Living with Family,...,Smoke,HADSbin,CurEdu,ExerciseDone,Sex,PP,LF,PH,S,BMIbin
0,3144076.0,90.0,G,None,M,5.0,62.0,21.0,Y,N,...,Y,Abnormal,1,0,1,1,0,1,1,3
1,8046964.0,96.0,G,None,M,4.5,69.0,18.0,Y,N,...,Y,Abnormal,1,0,1,1,0,1,1,4
2,7843714.0,112.0,G,None,M,5.2,68.0,20.0,Y,Y,...,Y,Abnormal,1,0,1,1,1,1,1,3
3,4036017.0,98.0,G,None,M,6.2,49.0,19.0,Y,Y,...,Y,Abnormal,1,0,1,1,1,1,1,0
4,9910417.0,104.0,PG,Moderate,F,5.6,77.0,22.0,N,Y,...,N,Borderline Abnormal,2,1,0,0,1,1,0,3

In [31]:
df.drop(['Current Education','Exercise','Gender','Peer Pressure','Living with Family','Past History','Smoke'],axis = 1,inplace = True)

In [32]:
df.head()

,StudentID,IQScore,Height,Weight,Age,HADSbin,CurEdu,ExerciseDone,Sex,PP,LF,PH,S,BMIbin
0,3144076.0,90.0,5.0,62.0,21.0,Abnormal,1,0,1,1,0,1,1,3
1,8046964.0,96.0,4.5,69.0,18.0,Abnormal,1,0,1,1,0,1,1,4
2,7843714.0,112.0,5.2,68.0,20.0,Abnormal,1,0,1,1,1,1,1,3
3,4036017.0,98.0,6.2,49.0,19.0,Abnormal,1,0,1,1,1,1,1,0
4,9910417.0,104.0,5.6,77.0,22.0,Borderline Abnormal,2,1,0,0,1,1,0,3

In [33]:
j = []
for i in df.itertuples(): 
    if((i[8]== 1 or i[8]== 2) and i[13] == 0 and (i[14]== 3 or i[14]== 1 or i[14]== 2) ):
        j.append(1)
    else:
        j.append(0)

In [34]:
j

[0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 ...]

In [35]:
df['isHealthy'] = j

In [36]:
df.head()

,StudentID,IQScore,Height,Weight,Age,HADSbin,CurEdu,ExerciseDone,Sex,PP,LF,PH,S,BMIbin,isHealthy
0,3144076.0,90.0,5.0,62.0,21.0,Abnormal,1,0,1,1,0,1,1,3,0
1,8046964.0,96.0,4.5,69.0,18.0,Abnormal,1,0,1,1,0,1,1,4,0
2,7843714.0,112.0,5.2,68.0,20.0,Abnormal,1,0,1,1,1,1,1,3,0
3,4036017.0,98.0,6.2,49.0,19.0,Abnormal,1,0,1,1,1,1,1,0,0
4,9910417.0,104.0,5.6,77.0,22.0,Borderline Abnormal,2,1,0,0,1,1,0,3,1

In [37]:
df.isna().sum()

StudentID        0
IQScore         10
Height           6
Weight           5
Age             14
HADSbin          0
CurEdu           0
ExerciseDone     0
Sex              0
PP               0
LF               0
PH               0
S                0
BMIbin           0
isHealthy        0
dtype: int64

In [38]:
df.dropna(inplace=True)

In [39]:
df.isna().sum()

StudentID       0
IQScore         0
Height          0
Weight          0
Age             0
HADSbin         0
CurEdu          0
ExerciseDone    0
Sex             0
PP              0
LF              0
PH              0
S               0
BMIbin          0
isHealthy       0
dtype: int64

In [40]:
df.count()

StudentID       43438
IQScore         43438
Height          43438
Weight          43438
Age             43438
HADSbin         43438
CurEdu          43438
ExerciseDone    43438
Sex             43438
PP              43438
LF              43438
PH              43438
S               43438
BMIbin          43438
isHealthy       43438
dtype: int64

In [41]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
5        False
6        False
7        False
10       False
11       False
12       False
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
30       False
31       False
         ...
43433    False
43434    False
43435    False
43436    False
43437    False
43438    False
43439    False
43440    False
43441    False
43442    False
43443    False
43444    False
43445    False
43446    False
43447    False
43448    False
43449    False
43454    False
43455    False
43456    False
43457    False
43458    False
43459    False
43460    False
43462    False
43463    False
43464    False
43465    False
43466    False
43467    False
Length: 43438, dtype: bool

In [42]:
df.drop_duplicates()

,StudentID,IQScore,Height,Weight,Age,HADSbin,CurEdu,ExerciseDone,Sex,PP,LF,PH,S,BMIbin,isHealthy
0,3144076.0,90.0,5.0,62.0,21.0,Abnormal,1,0,1,1,0,1,1,3,0
1,8046964.0,96.0,4.5,69.0,18.0,Abnormal,1,0,1,1,0,1,1,4,0
2,7843714.0,112.0,5.2,68.0,20.0,Abnormal,1,0,1,1,1,1,1,3,0
3,4036017.0,98.0,6.2,49.0,19.0,Abnormal,1,0,1,1,1,1,1,0,0
4,9910417.0,104.0,5.6,77.0,22.0,Borderline Abnormal,2,1,0,0,1,1,0,3,1
5,1596235.0,105.0,5.9,70.0,26.0,Borderline Abnormal,2,1,0,0,1,0,0,2,1
6,620289.0,92.0,4.7,71.0,22.0,Borderline Abnormal,2,1,0,0,1,0,0,4,0
7,9778010.0,99.0,5.6,48.0,23.0,Normal,2,1,0,0,1,0,1,1,0
10,6145392.0,96.0,5.7,53.0,28.0,Normal,2,2,1,0,1,0,0,1,1
11,7287561.0,89.0,4.9,45.0,13.0,Normal,0,0,1,0,0,1,0,2,0
12,9547882.0,111.0,4.9,35.0,12.0,Normal,0,0,1,0,0,0,1,0,0
13,4293181.0,87.0,5.4,49.0,13.0,Normal,0,0,0,1,0,0,1,1,0
14,5049198.0,104.0,5.3,41.0,12.0,Normal,0,1,0,0,1,0,0,0,0
15,871266.0,115.0,4.9,47.0,13.0,Normal,0,2,0,0,1,1,0,2,1
16,8900872.0,100.0,5.1,48.0,14.0,Normal,0,2,0,1,1,1,0,2,1
17,6848503.0,106.0,5.3,43.0,13.0,Normal,0,2,0,0,1,0,0,1,1
18,1129600.0,88.0,5.0,38.0,14.0,Normal,0,2,0,1,1,0,0,1,1
19,5546681.0,99.0,5.4,39.0,21.0,Abnormal,1,0,1,1,0,1,1,0,0
20,6552804.0,91.0,5.4,40.0,18.0,Abnormal,1,0,1,1,0,1,1,0,0
21,9443344.0,107.0,5.0,46.0,20.0,Abnormal,1,0,1,1,1,1,1,2,0
22,8991943.0,109.0,4.8,37.0,19.0,Abnormal,1,0,1,1,1,1,1,1,0
23,7147228.0,92.0,5.5,43.0,18.0,Abnormal,1,0,1,0,1,1,1,0,0
24,3103269.0,109.0,5.3,49.0,18.0,Abnormal,1,0,1,1,1,1,1,2,0
25,546779.0,115.0,5.1,43.0,18.0,Abnormal,1,1,1,1,0,1,1,1,0
26,1619123.0,104.0,4.9,46.0,27.0,Abnormal,2,0,1,1,0,1,1,2,0
27,9910930.0,112.0,4.9,39.0,26.0,Abnormal,2,0,1,1,0,1,1,1,0
28,4872049.0,92.0,5.3,44.0,26.0,Borderline Abnormal,2,0,1,1,0,1,1,1,0
29,1436066.0,108.0,5.2,43.0,27.0,Borderline Abnormal,2,0,0,1,0,0,0,1,0
30,6326932.0,94.0,4.8,44.0,25.0,Borderline Abnormal,2,0,0,0,0,0,1,2,0
31,1402573.0,110.0,5.2,46.0,24.0,Borderline Abnormal,2,1,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43433,4770263.0,88.0,5.2,70.0,13.0,Normal,0,0,1,0,0,1,0,3,0
43434,4156483.0,98.0,6.1,80.0,12.0,Normal,0,0,1,0,0,0,1,2,0
43435,1315119.0,107.0,4.5,53.0,13.0,Normal,0,0,0,1,0,0,1,3,0
43436,3804029.0,115.0,4.8,75.0,12.0,Normal,0,1,0,0,1,0,0,4,0
43437,7154369.0,105.0,4.9,77.0,13.0,Normal,0,2,0,0,1,1,0,4,0
43438,7677383.0,95.0,5.3,76.0,14.0,Normal,0,2,0,1,1,1,0,3,1
43439,5717939.0,86.0,4.7,52.0,13.0,Normal,0,2,0,0,1,0,0,3,1
43440,2256077.0,108.0,6.0,78.0,14.0,Normal,0,2,0,1,1,0,0,2,1
43441,5607902.0,108.0,4.8,80.0,21.0,Abnormal,1,0,1,1,0,1,1,4,0
43442,3041314.0,107.0,5.5,59.0,18.0,Abnormal,1,0,1,1,0,1,1,2,0
43443,676901.0,98.0,5.5,53.0,20.0,Abnormal,1,0,1,1,1,1,1,2,0
43444,4214801.0,89.0,4.6,68.0,19.0,Abnormal,1,0,1,1,1,1,1,4,0
43445,9367213.0,109.0,5.2,52.0,18.0,Abnormal,1,0,1,0,1,1,1,2,0
43446,6942577.0,114.0,4.7,63.0,18.0,Abnormal,1,0,1,1,1,1,1,4,0
43447,4753401.0,91.0,5.6,65.0,18.0,Abnormal,1,1,1,1,0,1,1,2,0
43448,17138.0,112.0,4.5,64.0,27.0,Abnormal,2,0,1,1,0,1,1,4,0
43449,2134630.0,103.0,5.9,55.0,26.0,Abnormal,2,0,1,1,0,1,1,1,0
43454,2644437.0,96.0,6.0,71.0,28.0,Borderline Abnormal,2,1,0,0,0,1,0,2,1
43455,9181474.0,104.0,5.0,77.0,22.0,Borderline Abnormal,2,1,0,0,0,1,0,4,0
43456,7597569.0,96.0,5.2,70.0,26.0,Borderline Abnormal,2,1,0,0,0,0,0,3,1
43457,1039769.0,96.0,4.7,50.0,22.0,Borderline Abnormal,2,1,0,0,0,0,0,2,1
43458,9888846.0,92.0,5.0,53.0,23.0,Normal,2,1,0,0,1,0,1,2,0
43459,3493712.0,115.0,4.5,49.0,27.0,Normal,2,2,1,0,1,0,0,3,1
43460,452430.0,95.0,6.2,68.0,24.0,Normal,2,2,1,0,1,0,0,2,1
43462,1055604.0,111.0,5.6,46.0,13.0,Normal,0,0,0,1,0,0,1,0,0
43463,5373529.0,99.0,4.8,55.0,12.0,Normal,0,1,0,0,1,0,0,3,1
43464,3620796.0,89.0,5.5,80.0,13.0,Normal,0,2,0,0,1,1,0,3,1
43465,6206208.0,94.0,4.9,50.0,14.0,Normal,0,2,0,1,1,1,0,2,1
43466,2687773.0,104.0,5.4,77.0,13.0,Normal,0,2,0,0,1,0,0,3,1
43467,3686126.0,102.0,4.5,60.0,14.0,Normal,0,2,0,1,1,0,0,4,0

In [43]:
df.drop(['StudentID'],axis = 1,inplace = True)

In [44]:
df.head()

,IQScore,Height,Weight,Age,HADSbin,CurEdu,ExerciseDone,Sex,PP,LF,PH,S,BMIbin,isHealthy
0,90.0,5.0,62.0,21.0,Abnormal,1,0,1,1,0,1,1,3,0
1,96.0,4.5,69.0,18.0,Abnormal,1,0,1,1,0,1,1,4,0
2,112.0,5.2,68.0,20.0,Abnormal,1,0,1,1,1,1,1,3,0
3,98.0,6.2,49.0,19.0,Abnormal,1,0,1,1,1,1,1,0,0
4,104.0,5.6,77.0,22.0,Borderline Abnormal,2,1,0,0,1,1,0,3,1

,Unnamed: 0,IQScore,Height,Weight,Age,HADSbin,CurEdu,ExerciseDone,Sex,PP,LF,PH,S,BMIbin,isHealthy
0,0,90.0,5.0,62.0,21.0,Abnormal,1,0,1,1,0,1,1,3,0
1,1,96.0,4.5,69.0,18.0,Abnormal,1,0,1,1,0,1,1,4,0
2,2,112.0,5.2,68.0,20.0,Abnormal,1,0,1,1,1,1,1,3,0
3,3,98.0,6.2,49.0,19.0,Abnormal,1,0,1,1,1,1,1,0,0
4,4,104.0,5.6,77.0,22.0,Borderline Abnormal,2,1,0,0,1,1,0,3,1

,IQScore,Height,Weight,Age,HADSbin,CurEdu,ExerciseDone,Sex,PP,LF,PH,S,BMIbin,isHealthy
0,90.0,5.0,62.0,21.0,Abnormal,1,0,1,1,0,1,1,3,0
1,96.0,4.5,69.0,18.0,Abnormal,1,0,1,1,0,1,1,4,0
2,112.0,5.2,68.0,20.0,Abnormal,1,0,1,1,1,1,1,3,0
3,98.0,6.2,49.0,19.0,Abnormal,1,0,1,1,1,1,1,0,0
4,104.0,5.6,77.0,22.0,Borderline Abnormal,2,1,0,0,1,1,0,3,1

In [9]:
scaler = StandardScaler()
dfx = scaler.fit_transform(df[['IQScore','Height','Weight','Age']])

In [11]:
dfx = pd.DataFrame(dfx)

In [12]:
dfx.head()

          0         1         2         3
0 -1.363646 -0.576701  0.115066  0.063909
1 -0.660853 -1.676257  0.668543 -0.513479
2  1.213260 -0.136879  0.589475 -0.128554
3 -0.426589  2.062233 -0.912821 -0.321016
4  0.276203  0.742766  1.301088  0.256372

In [13]:
dfx.isna().sum()

0    0
1    0
2    0
3    0
dtype: int64

In [14]:
dfx.shape

(43438, 4)

In [15]:
dfx['ExerciseDone'] = df['ExerciseDone']

In [16]:
dfx

              0         1         2         3  ExerciseDone
0     -1.363646 -0.576701  0.115066  0.063909             0
1     -0.660853 -1.676257  0.668543 -0.513479             0
2      1.213260 -0.136879  0.589475 -0.128554             0
3     -0.426589  2.062233 -0.912821 -0.321016             0
4      0.276203  0.742766  1.301088  0.256372             1
...         ...       ...       ...       ...           ...
43433 -0.309457 -1.016523 -0.438412 -1.668255             1
43434 -1.480778  0.522855  1.538293 -1.475792             2
43435 -0.895117 -0.796612 -0.833753 -1.283330             2
43436  0.276203  0.302944  1.301088 -1.475792             2
43437  0.041939 -1.676257 -0.043071 -1.283330             2

[43438 rows x 5 columns]

In [17]:
dfx.isna().sum()

0               0
1               0
2               0
3               0
ExerciseDone    0
dtype: int64

In [19]:
df.columns

Index(['IQScore', 'Height', 'Weight', 'Age', 'HADSbin', 'CurEdu',
       'ExerciseDone', 'Sex', 'PP', 'LF', 'PH', 'S', 'BMIbin', 'isHealthy'],
      dtype='object')

In [20]:
dfx['Sex'] = df['Sex']
dfx['PP'] = df['PP']
dfx['LF'] = df['LF']
dfx['PH'] = df['PH']
dfx['S'] = df['S']
dfx['BMIbin'] = df['BMIbin']
dfx['isHealthy'] = df['isHealthy']
dfx['HADSbin'] = df['HADSbin']

In [21]:
dfx.head()

,0,1,2,3,ExerciseDone,CurEdu,Sex,PP,LF,PH,S,BMIbin,isHealthy,HADSbin
0,-1.363646,-0.576701,0.115066,0.063909,0,1,1,1,0,1,1,3,0,Abnormal
1,-0.660853,-1.676257,0.668543,-0.513479,0,1,1,1,0,1,1,4,0,Abnormal
2,1.213260,-0.136879,0.589475,-0.128554,0,1,1,1,1,1,1,3,0,Abnormal
3,-0.426589,2.062233,-0.912821,-0.321016,0,1,1,1,1,1,1,0,0,Abnormal
4,0.276203,0.742766,1.301088,0.256372,1,2,0,0,1,1,0,3,1,Borderline Abnormal

In [22]:
dfx.isna().sum()

0               0
1               0
2               0
3               0
ExerciseDone    0
CurEdu          0
Sex             0
PP              0
LF              0
PH              0
S               0
BMIbin          0
isHealthy       0
HADSbin         0
dtype: int64

In [24]:
X = dfx.drop(['HADSbin'],axis = 1)
y = dfx['HADSbin']
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [25]:
model = DecisionTreeClassifier()
model.fit(X_train, y_train)
y_predict = model.predict(X_test)
print('Accuracy: ',accuracy_score(y_test, y_predict))

Accuracy:  0.8575506445672192

In [27]:
model = ExtraTreesClassifier()
model.fit(X_train, y_train)
y_predict = model.predict(X_test)
print('Accuracy: ',accuracy_score(y_test, y_predict))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

Accuracy:  0.8569060773480663

In [28]:
model = GaussianNB()
model.fit(X_train, y_train)
y_predict = model.predict(X_test)
print('Accuracy: ',accuracy_score(y_test, y_predict))

Accuracy:  0.6985267034990792

In [29]:
model = RandomForestClassifier()
model.fit(X_train, y_train)
y_predict = model.predict(X_test)
print('Accuracy: ',accuracy_score(y_test, y_predict))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

Accuracy:  0.8569060773480663

In [30]:
model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train)
y_predict = model.predict(X_test)
print('Accuracy: ',accuracy_score(y_test, y_predict))

Accuracy:  0.8271639042357274

In [32]:
from sklearn.svm import SVC
model = SVC(gamma='auto')
model.fit(X_train, y_train)
y_predict = model.predict(X_test)
print('Accuracy: ',accuracy_score(y_test, y_predict))

Accuracy:  0.8475138121546961

In [34]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)
y_predict = model.predict(X_test)
print('Accuracy: ',accuracy_score(y_test, y_predict))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

Accuracy:  0.7457642725598527

In [35]:
from sklearn import model_selection
from sklearn.ensemble import AdaBoostClassifier
kfold = model_selection.KFold(n_splits=10, random_state=7)
model = AdaBoostClassifier(n_estimators=30, random_state=7)
results = model_selection.cross_val_score(model, X_train, y_train, cv=kfold)
print(results.mean())

0.7915766353359333

In [36]:
model1 = DecisionTreeClassifier()
model2 = ExtraTreesClassifier()
model3 = RandomForestClassifier()
model4 = LogisticRegression()
model5 = SVC(gamma='auto')
model6 = KNeighborsClassifier(n_neighbors=3)
model7 = GaussianNB()

model1.fit(X_train, y_train)
model2.fit(X_train, y_train)
model3.fit(X_train, y_train)
model4.fit(X_train, y_train)
model5.fit(X_train, y_train)
model6.fit(X_train, y_train)
model7.fit(X_train, y_train)
y_predict1 = model1.predict(X_test)
y_predict2 = model2.predict(X_test)
y_predict3 = model3.predict(X_test)
y_predict4 = model4.predict(X_test)
y_predict5 = model5.predict(X_test)
y_predict6 = model6.predict(X_test)
y_predict7 = model7.predict(X_test)

print('AccuracyDT: ',accuracy_score(y_test, y_predict1))
print('AccuracyET: ',accuracy_score(y_test, y_predict2))
print('AccuracyRFT: ',accuracy_score(y_test, y_predict3))
print('AccuracyLR: ',accuracy_score(y_test, y_predict4))
print('AccuracySVM: ',accuracy_score(y_test, y_predict5))
print('AccuracyKNN: ',accuracy_score(y_test, y_predict6))
print('AccuracyNB: ',accuracy_score(y_test, y_predict7))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

AccuracyDT:  0.8575506445672192
AccuracyET:  0.857366482504604
AccuracyRFT:  0.8572744014732965
AccuracyLR:  0.7457642725598527
AccuracySVM:  0.8475138121546961
AccuracyKNN:  0.8271639042357274
AccuracyNB:  0.6985267034990792

In [37]:
from sklearn.ensemble import BaggingClassifier

In [38]:
clf = BaggingClassifier(base_estimator=SVC(gamma = 'auto'),n_estimators=10, random_state=0).fit(X, y)
y_predictx = clf.predict(X_test)
print('AccuracyBagging: ',accuracy_score(y_test, y_predictx))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

AccuracyBagging:  0.850828729281768